language: java

jdk:
  - oraclejdk7
  
services:
 - docker

install:
 - docker build -t springmvc_template:v3.0 .
 - docker run -d -p 192.168.1.203:8082:8081 --name springmvc_template springmvc_template:v3.0


